# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory within the container
WORKDIR /app

# Copy package.json and package-lock.json to the container's working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code to the container's working directory
COPY . .

# Expose the port that the app will run on
EXPOSE 5000

# Define the command to run when the container starts
CMD [ "node", "index.js" ]
